deathMessages = [
    ' took the L.',
    ' fell out of the world.',
    ' committed toaster bath.',
    ' decided to commit die.',
    ' got ora ora\'d to death.',
    '\'s soul left their body.',
    ' was put through a pepper grinder.',
    ' died in a hole.',
    ' procrastinated on their homework.',
    ' forgot to turn off the oven.',
    ' went skydiving attached to a fridge.',
    ' pressed alt+f4.',
    ' was struck by lightning.',
    ' forgot to study for a test.',
    ' contracted COVID-19.',
    ' drank too much weed.',
    ' vaped a fifth of vodka.',
    ' was crushed by an anvil.',
    ' tried to swim in lava.',
    ' dug straight down.',
    ' stayed up too late watching anime.',
    ' donated their life savings to Pokimane.',
    ' misspelled among us.',
    ' needs to GIT GUD!',
    ' gooottttttt dunked on!!!',
    ' has committed neck rope.',
    ' was sent to the gulag.',
    ' went to Brazil.',
    ' did not juju on that beat.',
    ' got deported.',
    ' committed tax evasion.',
    ' stepped on some legoes.',
    ' did not expect the spanish inquisition.',
    ' ordered pineapple on pizza.',
    ' read 177013.',
]
